// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file example/article/v1/article.proto (package example.article.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { ListArticleResponse } from "./article_pb.js";

/**
 * 記事サービス
 *
 * @generated from service example.article.v1.ArticleService
 */
export const ArticleService = {
  typeName: "example.article.v1.ArticleService",
  methods: {
    /**
     * ユーザを取得
     *
     * @generated from rpc example.article.v1.ArticleService.ListArticle
     */
    listArticle: {
      name: "ListArticle",
      I: Empty,
      O: ListArticleResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
  }
} as const;

