// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file example/user/v1/internal.proto (package example.user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetUserRequest, GetUserResponse } from "./internal_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * 内部呼び出し用のユーザサービス
 *
 * @generated from service example.user.v1.InternalUserService
 */
export const InternalUserService = {
  typeName: "example.user.v1.InternalUserService",
  methods: {
    /**
     * ユーザを取得
     *
     * @generated from rpc example.user.v1.InternalUserService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: GetUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

